# Generated by Django 4.2 on 2023-08-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0009_remove_tweet_users_retweet_tweet_retweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='retweet',
            new_name='retweet_from',
        ),
    ]
