# Generated by Django 4.2 on 2023-08-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0010_rename_retweet_tweet_retweet_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweet_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
